<a href="https://colab.research.google.com/github/abhinav-m/data-science-bootcamp/blob/master/Udemy-Machine-Learning-A-Z/Part-1-Data-Preprocessing/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [2]:
dataset = pd.read_csv('Data.csv')
# Matrix of features
# All columns except last column
X = dataset.iloc[:,:-1].values
# Dependant variable y
# No range, select last column
y = dataset.iloc[:,-1].values

In [3]:
# Print features
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [4]:
# Print Dependant variable y
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [5]:
# Helps in preprocessing data
from sklearn.impute import SimpleImputer

# Creating object
# Replace missing NaN values by strategy as mean
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')

# Missing salary and age columns ( as they are numerical columns )
# Should be done on all numerical columns to replace missing data for big data
# sets.
X[:,1:3] = imputer.fit(X[:,1:3]).transform(X[:,1:3])


In [6]:
# Matrix with missing values replaced as average

print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [7]:
# Importing the encoding and one hot encoding libraries from sklearn
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Second argument specifies what to do with the remainder of the matrix columns ie, to leave them as it is and not encode.
ct = ColumnTransformer(transformers= [("encoder",OneHotEncoder(),[0])], remainder='passthrough')

# Don't need to fit and transform as imputer in seperate steps, can do it in one go.
X = np.array(ct.fit_transform(X))

In [8]:
# Print the transformed array
'''
  Categorical data such as different countries is encoded 
  here using a technique called One Hot Encoder 
  This is better than using 0 1 2 3 (series encoder) 
  As this prevents ML models to think that there is a 
  "order" to the countries. Thus vectors to represent 
  the countries as 
  [0 0 1] [0 1 0] [1 0 0] are used.
'''
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [9]:
from sklearn.preprocessing import LabelEncoder

# Creating object of encoder which will transform y into 0 and 1
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
# Print transformed data
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [11]:
# Feature scaling is always done after splitting the test set.
# As this calculates the mean and s.d over all the values in the dataset.
# Therefore, to avoid data leakage Feature scaling is applied later on.

from sklearn.model_selection  import train_test_split

# Training tests to split, and size
# Last value fixes the random seed
X_train , X_test ,Y_train, Y_test = train_test_split(X,y,test_size = 0.2,random_state=1)

In [12]:
# Training Set X
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [13]:
# Training Set y
print(Y_train)

[0 1 0 0 1 1 0 1]


In [14]:
# Test Set X
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [15]:
# Test Set y
print(Y_test)

[0 1]


## Feature Scaling

In [17]:
# Can be done in two ways Standardisation and Normalisation
# Standardisation - subtract by mean divide by S.D between -3 and + 3 -> Works well all the time
# Normalisation - subtract by min divide by range (Max - Min) Results in value b/w 0 and 1 -> Works well with normal distribution
# Always done after splitting of dataset.

from sklearn.preprocessing import StandardScaler

#Feature scaling is applied to numerical values, and in this case first countries hot encoded data is ignored.
sc = StandardScaler()

# Take remaining columns except one hot encoded values
# Fit -> Get mean and S.D
# Transform -> Apply to values , below method does both
X_train[:,3:] = sc.fit_transform(X_train[:,3:])

# Important to apply same scaler to this (DOUBT ) as both scalers working on same model.
X_test[:,3:] = sc.transform(X_test[:,3:])

In [18]:
# Print scaled X_train
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [19]:
# Print scaled X_test
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
