<a href="https://colab.research.google.com/github/abhinav-m/data-science-bootcamp/blob/master/Udemy-Machine-Learning-A-Z/Part-1-Data-Preprocessing/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [4]:
dataset = pd.read_csv('Data.csv')
# Matrix of features
# All columns except last column
X = dataset.iloc[:,:-1].values
# Dependant variable y
# No range, select last column
y = dataset.iloc[:,-1].values

In [5]:
# Print features
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [6]:
# Print Dependant variable y
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [7]:
# Helps in preprocessing data
from sklearn.impute import SimpleImputer

# Creating object
# Replace missing NaN values by strategy as mean
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')

# Missing salary and age columns ( as they are numerical columns )
# Should be done on all numerical columns to replace missing data for big data
# sets.
X[:,1:3] = imputer.fit(X[:,1:3]).transform(X[:,1:3])


In [8]:
# Matrix with missing values replaced as average

print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [11]:
# Importing the encoding and one hot encoding libraries from sklearn
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Second argument specifies what to do with the remainder of the matrix columns ie, to leave them as it is and not encode.
ct = ColumnTransformer(transformers= [("encoder",OneHotEncoder(),[0])], remainder='passthrough')

# Don't need to fit and transform as imputer in seperate steps, can do it in one go.
X = np.array(ct.fit_transform(X))

In [12]:
# Print the transformed array
'''
  Categorical data such as different countries is encoded 
  here using a technique called One Hot Encoder 
  This is better than using 0 1 2 3 (series encoder) 
  As this prevents ML models to think that there is a 
  "order" to the countries. Thus vectors to represent 
  the countries as 
  [0 0 1] [0 1 0] [1 0 0] are used.
'''
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [15]:
from sklearn.preprocessing import LabelEncoder

# Creating object of encoder which will transform y into 0 and 1
le = LabelEncoder()
y = le.fit_transform(y)

In [16]:
# Print transformed data
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

## Feature Scaling